---
title: "Informe"
author: "Martínez Matías"
date: "05 de julio de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introducción

Se pretende conocer el comportamiento en la producción de energía solar y eólica a nivel global mediante visualizaciones interactivas que permitan al usuario una experiencia mas amena. Se centrara en el uso de shiny, ya que es de interés fundamental en dicho análisis estadístico su funcional y acorde aplicación.

### Justificación

El objetivo fundamental es la aplicación de nuevos métodos estadísticos de visualización, profundizando en su correcta implementación y con gran interés en la captación de experiencia y nuevos conocimientos en áreas de visualización y uso del entorno estadístico R.

### Preguntas a responder

- ¿Qué comportamiento posee la producción de energía solar y eólica para el periodo dado?
- ¿Cuál es la media para ambos tipos de energías y que países superan la misma?
- 



### Hipótesis

- Dada la concientización con el medio ambiente, los países con mayor IDH generan la mayor producción de tales energías.

- Los anteriormente mencionados superan ampliamente la media de producción de manera constante en el transcurso de los años.



## Marco Teórico


### Fuente de datos


### Base de datos


### Descripción de las variables

### Nomenclatura estadística









